# Path
dataset_path: ../data/raw/bank-full.csv
dataset_delimiter: ;
train_path:
- ../data/processed/X_train.pkl
- ../data/processed/y_train.pkl
valid_path:
- ../data/processed/X_valid.pkl
- ../data/processed/y_valid.pkl
test_path:
- ../data/processed/X_test.pkl
- ../data/processed/y_test.pkl
train_processed_path:
- ../data/processed/X_train_processed.pkl
- ../data/processed/y_train_processed.pkl
valid_processed_path:
- ../data/processed/X_valid_processed.pkl
- ../data/processed/y_valid_processed.pkl
test_processed_path:
- ../data/processed/X_test_processed.pkl
- ../data/processed/y_test_processed.pkl
model_path: ../models/model.pkl
training_log_path: ../log/training_log.json

# Columns by data type
int_columns:
- age
- balance
- day
- duration
- campaign
- pdays
- previous
nominal_columns:
- job
- marital
- contact
- default
- housing
- loan
ordinal_columns:
- education
- month
- poutcome

# Predictors and label
label: y
predictors:
- age
- job
- marital
- education
- default
- balance
- housing
- loan
- contact
- day
- month
- duration
- campaign
- pdays
- previous
- poutcome

# Range of data
range_age:
- 18
- 95
range_balance:
- -8019
- 102127
range_day:
- 1
- 31
range_duration:
- 0
- 4918
range_campaign:
- 1
- 63
range_pdays:
- -1
- 871
range_previous:
- 0
- 275

# Splitting size
test_size: 0.3
valid_size: 0.5

# Columns to label encoding
label_encoding_columns:
- education
- default
- housing
- loan
- contact
- month
- "y"

# Columns to one-hot encoding
one_hot_encoding_columns:
- job
- poutcome

# Label encoding
education_code:
  primary: 0
  secondary: 1
  tertiary: 2
default_code:
  "no": 0
  "yes": 1
housing_code:
  "no": 0
  "yes": 1
loan_code:
  "no": 0
  "yes": 1
contact_code:
  unknown: 0
  cellular/telephone: 1
month_code:
  jan: 0
  feb: 1
  mar: 2
  apr: 3
  may: 4
  jun: 5
  jul: 6
  aug: 7
  sep: 8
  oct: 9
  nov: 10
  dec: 11
y_code:
  "no": 0
  "yes": 1

# Job re-categorize
job_new_category:
  keep:
    - blue-collar
    - student
    - retired
  replace: others

# Education replace
education_replace:
  from:
    - secondary
    - unknown
  to: secondary

# Merge contact
contact_merge:
  from:
    - cellular
    - telephone
  to: cellular/telephone

# Pdays replace
pdays_replace:
  from: -1
  to: 999